/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_12 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] sout
  );
  
  
  
  wire [16-1:0] M_mul_mul;
  reg [8-1:0] M_mul_a;
  reg [8-1:0] M_mul_b;
  multiply_13 mul (
    .a(M_mul_a),
    .b(M_mul_b),
    .mul(M_mul_mul)
  );
  
  always @* begin
    M_mul_a = a[0+7-:8];
    M_mul_b = b[0+7-:8];
    
    case (alufn[0+1-:2])
      default: begin
        sout = a;
      end
      2'h0: begin
        sout = a << b[0+3-:4];
      end
      2'h1: begin
        sout = a >> b[0+3-:4];
      end
      2'h3: begin
        sout = $signed(a) >>> b[0+3-:4];
      end
      2'h2: begin
        sout = M_mul_mul;
      end
    endcase
  end
endmodule
