/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module stateCounter_3 (
    input clk,
    input rst,
    output reg inc_state1,
    output reg inc_state2,
    output reg inc_state3
  );
  
  
  
  reg [21:0] M_stateCounter1_d, M_stateCounter1_q = 1'h0;
  
  reg [20:0] M_stateCounter2_d, M_stateCounter2_q = 1'h0;
  
  reg [19:0] M_stateCounter3_d, M_stateCounter3_q = 1'h0;
  
  always @* begin
    M_stateCounter3_d = M_stateCounter3_q;
    M_stateCounter2_d = M_stateCounter2_q;
    M_stateCounter1_d = M_stateCounter1_q;
    
    inc_state1 = M_stateCounter1_q[21+0-:1];
    M_stateCounter1_d = M_stateCounter1_q + 1'h1;
    if (M_stateCounter1_q[21+0-:1] == 1'h1) begin
      M_stateCounter1_d[21+0-:1] = 1'h0;
    end
    inc_state2 = M_stateCounter2_q[20+0-:1];
    M_stateCounter2_d = M_stateCounter2_q + 1'h1;
    if (M_stateCounter2_q[20+0-:1] == 1'h1) begin
      M_stateCounter2_d[20+0-:1] = 1'h0;
    end
    inc_state3 = M_stateCounter3_q[19+0-:1];
    M_stateCounter3_d = M_stateCounter3_q + 1'h1;
    if (M_stateCounter3_q[19+0-:1] == 1'h1) begin
      M_stateCounter3_d[19+0-:1] = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_stateCounter1_q <= 1'h0;
    end else begin
      M_stateCounter1_q <= M_stateCounter1_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_stateCounter2_q <= 1'h0;
    end else begin
      M_stateCounter2_q <= M_stateCounter2_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_stateCounter3_q <= 1'h0;
    end else begin
      M_stateCounter3_q <= M_stateCounter3_d;
    end
  end
  
endmodule
